language: objective-c
os: osx
osx_image: xcode8.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    global:
        - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1

script:
    - set -o pipefail
    - xcodebuild clean test -workspace Upsurge.xcworkspace -scheme "Upsurge OSX" | xcpretty
    - xcodebuild clean test -workspace Upsurge.xcworkspace -scheme "Upsurge iOS" -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
